Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import (
    search,
    IndexView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    about,
    contact,
    policy,
    newsletter,
    AboutSikkim,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('blog/', PostListView.as_view(), name='post-list'),
    path('search/', search, name='search'),
    path('newsletter/', newsletter, name='newsletter'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('privacy&policy/',policy,name='policy'),
    path('AboutSikkim/<pk>/', AboutSikkim.as_view(), name='sikkim'),

]


urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = 'posts.views.not_found'
handler500 = 'posts.views.server_error'
handler403 = 'posts.views.permission_denied'
handler400 = 'posts.views.bad_request'

posts/models.py
from tinymce.models import HTMLField
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
import uuid

User = get_user_model()


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'PostView'
        verbose_name_plural = 'Postviews'
        db_table = 'tbl_postview'
        managed = True

    def __str__(self):
        return self.user.username


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'
        db_table = 'tbl_author'
        managed = True

    def __str__(self):
        return self.user.username
    


class Category(models.Model):
    title = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        db_table = 'tbl_category'
        managed = True

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        db_table = 'tbl_comment'
        managed = True

    def __str__(self):
        return self.user.username


class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    overview = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    content = HTMLField()
    # comment_count = models.IntegerField(default = 0)
    # view_count = models.IntegerField(default = 0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField()
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Add Blog'
        db_table = 'tbl_post'
        managed = True

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'pk': self.pk
        })

    def get_update_url(self):
        return reverse('post-update', kwargs={
            'pk': self.pk
        })

    def get_delete_url(self):
        return reverse('post-delete', kwargs={
            'pk': self.pk
        })

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

class ContactUs(models.Model):
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Contact Us'
        verbose_name_plural = 'Contact Us'
        db_table = 'tbl_contactus'
        managed = True

    def __str__(self):
        return self.fname + '-  ' +self.email
    
    
class Signup(models.Model):
    email = models.EmailField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Newsletter'
        verbose_name_plural = 'Newsletters'
        db_table = 'tbl_newsletter'
        managed = True

    def __str__(self):
        return self.email
    
    
class AllaboutSikkim(models.Model):
    bg_image = models.ImageField() 
    bg_heading = models.CharField(max_length=10)
    heading1 =  models.TextField()
    heading2 = models.TextField()
    image1 = models.ImageField()
    sub_heading1 = models.TextField()
    image2 = models.ImageField()
    sub_heading2 = models.TextField()
    heading3 = models.TextField()
    
    class Meta:
        verbose_name = 'All About Sikkim'
        verbose_name_plural = 'Add About Sikkim'
        db_table = 'tbl_aboutsikkim'
        managed = True

    def __str__(self):
        return self.bg_heading
    
    def get_absolute_url(self):
        return reverse('sikkim', kwargs={
            'pk': self.pk
        })

posts/forms.py
from .models import Signup
from django import forms
from tinymce import TinyMCE
from .models import Post, Comment, ContactUs


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'overview', 'content', 'thumbnail','categories', 'featured', 'previous_post', 'next_post')


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4'
    }))

    class Meta:
        model = Comment
        fields = ('content',)


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ('fname','lname','email','subject','message',)


class EmailSignupForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={
        "type": "email",
        "name": "email",
        "id": "email",
        "placeholder": "Type your email address",
    }), label="")

    class Meta:
        model = Signup
        fields = ('email', )

posts/views.py
from django.db.models import Count, Q
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from posts.forms import CommentForm, PostForm
from posts.models import Post, Author, PostView, AllaboutSikkim
from posts.forms import EmailSignupForm
from posts.models import Signup
from .forms import ContactForm

form = EmailSignupForm()


def get_author(user):
    '''
    DOCSTRING : Information About Function
    INPUT : Get author object 
    OUTPUT : check the author exist or not
    '''
    qs = Author.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None


class SearchView(View):
    '''
        DOCSTRING : INFORMATION ABOUT The SEARCH FUNCTION 
        INPUT : GET THE INPUT FROM THE QUERY SET
        OUTPUT : GIVES THE USER APPROPIATE RESUTE ABOUT ITS SERACH
        '''

    def get(self, request, *args, **kwargs):
        queryset = Post.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(overview__icontains=query)
            ).distinct()
        context = {
            'queryset': queryset

        }
        if queryset:
            return render(request, 'search_results.html', context)
        else:
            return render(request, 'search_results.html', context=True)


def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)
        ).distinct()
    context = {
        'queryset': queryset
    }
    return render(request, 'search_results.html', context)


def get_category_count():
    queryset = Post \
        .objects \
        .values('categories__title') \
        .annotate(Count('categories__title'))
    return queryset


class IndexView(View):
    form = EmailSignupForm()

    def get(self, request, *args, **kwargs):
        featured = Post.objects.filter(featured=True)[0:1]
        latest = Post.objects.order_by('-timestamp')[0:3]
        sikkim = AllaboutSikkim.objects.all()
        context = {
            'object_list': featured,
            'latest': latest,
            'sikkim': sikkim,
            'form': self.form,
            'title': 'Home'
        }
        return render(request, 'index.html', context)


def newsletter(request):
    form = EmailSignupForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            email_signup_qs = Signup.objects.filter(email=form.instance.email)
            if email_signup_qs.exists():
                messages.info(request, "You are already subscribed")
            else:
                form.save()
                messages.info(request, "Sucessfully subscribed")
    return HttpResponseRedirect('/')


class PostListView(ListView):
    model = Post
    template_name = 'blog.html'
    context_object_name = 'queryset'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['title'] = 'Blog'
        return context


class AboutSikkim(DetailView):
    model = AllaboutSikkim
    template_name = 'allsikkim/aboutSikkim.html'
    context_object_name = 'sikkim'


class PostDetailView(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'
    form = CommentForm()

    def get_object(self):
        obj = super().get_object()
        if self.request.user.is_authenticated:
            PostView.objects.get_or_create(
                user=self.request.user,
                post=obj
            )
        return obj

    def get_context_data(self, **kwargs):
        category_count = get_category_count()
        most_recent = Post.objects.order_by('-timestamp')[:3]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['page_request_var'] = "page"
        context['category_count'] = category_count
        context['form'] = self.form
        context['title'] = 'Post'
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'pk': post.pk
            }))


class PostCreateView(CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context

    def form_valid(self, form):
        form.instance.author = get_author(self.request.user)
        form.save()
        return redirect(reverse("post-detail", kwargs={
            'pk': form.instance.pk
        }))


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update'
        return context

    def form_valid(self, form):
        form.instance.author = get_author(self.request.user)
        form.save()
        return redirect(reverse("post-detail", kwargs={
            'pk': form.instance.pk
        }))


class PostDeleteView(DeleteView):
    model = Post
    success_url = '/blog'
    template_name = 'post_confirm_delete.html'


def about(request):
    title = 'About'
    return render(request, 'about.html', {'title': title})


def contact(request):
    title = 'Contact'
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'title': title, 'form': form})


def policy(request):
    title = 'Privacy'
    return render(request, 'privacy&policy.html', {'title': title})


def server_error(request, *args, **kwargs):
    return render(request, 'errors/404.html', status=404)


def not_found(request, *args, **kwargs):
    return render(request, 'errors/500.html', status=500)


def permission_denied(request, *args, **kwargs):
    return render(request, 'errors/404.html', status=403)


def bad_request(request, *args, **kwargs):
    return render(request, 'errors/500.html', status=400)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">

      <div class="card card my-5">
        <div class="row">
          <div class="col-sm-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
            <div style="width: 100%; text-align: center; padding: 50px 0 5px"><strong><span class="h5">About</span></strong></div>
            {% for da in sikkim %}
               {{da}}
            {% endfor %}
   </div>
      </div>
   </div>
      </div>
   {% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

{% include "includes/head.html" %}

<body>

    {% include 'includes/header.html' %}

    {% if messages %}
        <div class="messages alert alert-secondary alert-dismissible fade show" role="alert">
            {% for message in messages %}
            <strong>!! {{ message }} !!</strong> 
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {% endfor %}
        </div>
    {% endif %}
    {% block content %}
    {% endblock content %}

    {% include 'includes/footer.html' %}
    {% include 'includes/scripts.html' %}

</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in queryset %}
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    {% comment %} <div class="date meta-last">20 May | 2016</div> {% endcomment %}
                    <div class="category">
                    {% for cat in post.categories.all %}
                    <a href="#">{{ cat }}</a>
                    {% endfor %}
                    </div>
                  </div><a href="{{ post.get_absolute_url }}">
                    <h3 class="h4">{{ post.title }}</h3></a>
                  <p class="text-muted">{{ post.overview }}</p>
                  <footer class="post-footer d-flex align-items-center">
                    <a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                      <div class="title"><span>{{ post.author.user.first_name }} {{ post.author.user.last_name }}
</span></div>
                    </a>
                    <div class="date meta-last">&nbsp;<i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                    <!-- <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div> -->
                  </footer>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}                
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>

            {% if is_paginated %}
            
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if page_obj.has_previous %}                
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.number }}" class="page-link active">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
            
            {% endif %}   
          </div>
        </main>
        {% include 'includes/sidebar.html' with most_recent=most_recent category_count=category_count %}
      </div>
    </div>

{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!-- <section style="background: url(/static/a_images/8.JPG); background-size: cover; background-position: center up;" class="divider">
    <div class="container">
        <div class="row">
            <h1 style="text-align:center">{{ title }} us</h1>
        </div>
    </div>

</section> -->
<div class="container">
        <h1 style="text-align:center;">{{ title }} us</h1>
</div>
<div class="container"> 
    <div class="row">
    <div class="col-md-7 mb-5">
<!--<form method="post">-->
<!--    {% csrf_token %}-->
<!--    {{ form|crispy }}-->
<!--    {{ from.fname }}-->
<!--    <button type="submit" class="btn btn-outline-secondary pull-right">Send Message</button>-->
<!--</form>-->

        <form method="post">
            {% csrf_token %}

<div id="div_id_fname" class="form-group"> <label for="id_fname" class="col-form-label  requiredField">
                First name</label> <div class="">
    <input type="text" name="fname" maxlength="100" class="textinput textInput form-control" required="" id="id_fname">
</div>
</div>
            <div id="div_id_lname" class="form-group">
                <label for="id_lname" class="col-form-label  requiredField">Last name</label>
            <div class="">
                <input type="text" name="lname" maxlength="100" class="textinput textInput form-control" required="" id="id_lname">
            </div>
            </div>
            <div id="div_id_email" class="form-group">
                <label for="id_email" class="col-form-label  requiredField">Email</label>
                <div class="">
                    <input type="email" name="email" maxlength="254" class="emailinput form-control" required="" id="id_email">
                </div>
            </div>
            <div id="div_id_subject" class="form-group">
                <label for="id_subject" class="col-form-label  requiredField">Subject</label>
                <div class="">
                    <input type="text" name="subject" maxlength="100" class="textinput textInput form-control" required="" id="id_subject">
                </div>
            </div>
            <div id="div_id_message" class="form-group"> <label for="id_message" class="col-form-label  requiredField">Message</label>
                <div class="">
                    <textarea name="message" cols="40" rows="10" class="textarea form-control" required="" id="id_message">

                    </textarea>
                </div>
            </div>
    <button type="submit" class="btn btn-outline-secondary pull-right">Send Message</button>
</form>

</div>
      <div class="col-md-5">
      <div class="p-4 mb-3 bg-white">
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">Bulbulay, East Sikkim, Gangtok, Sikkim 737103</p>
              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>
              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#">ayubrai@domain.com</a></p>
      </div>
       <div class="p-4 mb-3 bg-white">
           <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d226940.40731325233!2d88.53899262862284!3d27.283634235716928!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39e6a56a5805eafb%3A0xd7f7c40985d31b5d!2sEast%20Sikkim%2C%20Sikkim!5e0!3m2!1sen!2sin!4v1569229903244!5m2!1sen!2sin" width="420" height="360" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
         </div>
      </div>
</div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section style="background: url(static/a_images/4.JPG); background-size: cover; background-position: center center"
  class="hero">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <h1>MOMENTS ARE ALWAYS MEANT TO BE.</h1>
      </div>
    </div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i>Discover More</a>
  </div>
</section>
<section class="intro">
  <div class="container">
    <div class="row">
      <div class="col col-lg-8">
        <h2 class="h3">Some great intro here</h2>
        <p class="text-big">Sikkim is a state in <strong>northeast India </strong> , bordered by Bhutan, Tibet and
          Nepal. Part of the Himalayas, the area has a dramatic landscape that includes<strong> India’s highest
            mountain, 8,586m Kangchenjunga</strong>. Sikkim is also home to glaciers, alpine meadows and thousands of
          varieties of wildflowers. Steep paths lead to hilltop Buddhist monasteries such as Pemayangtse, which dates to
          the early 1700s.
        </p>
      </div>
        <div class="card col-md-auto mx-auto">
          <div class="card-header mx-auto">
            <h2 class="h3">All about Sikkim</h2>
            <hr>
              <ul>
                {% for da in sikkim %}
                <li><a href="AboutSikkim/{{da.pk}}" class="text-big">{{da}}</a></li>
                {% endfor %}
                <hr>
              </ul>
              <h6 style="text-align:center">...</h6>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
  <section class="featured-posts no-padding-top">
    <div class="container">
      <!--featured Post-->
      {% for obj in object_list %}
      <div class="row d-flex align-items-stretch">
        {% if not forloop.first and not forloop.last %}
        <div class="image col-lg-5"><img src="{{ obj.thumbnail.url }}" alt="..."></div>
        {% endif %}
        <div class="text col-lg-7">
          <div class="text-inner d-flex align-items-center">
            <div class="content">
              <header class="post-header">
                <div class="category">
                  {% for cat in obj.categories.all %}
                  <a href="#">{{ cat }}</a>
                  {% endfor %}
                </div>
                <a href="post/{{obj.pk}}">
                  <h2 class="h4">{{ obj.title }}</h2>
                </a>
              </header>
              <p>{{ obj.overview|linebreaks|truncatechars:200 }}</p>
              <footer class="post-footer d-flex align-items-center"><a href="#"
                  class="author d-flex align-items-center flex-wrap">
                  <div class="avatar"><img src="{{ obj.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><span>
                    {{ obj.author.user.first_name }} {{ obj.author.user.last_name }}
                  </span></div>
                </a>
                
                <div class="date"> &nbsp;<i class="icon-clock"></i> {{ obj.timestamp|timesince }} ago</div>
              </footer>
            </div>
          </div>
        </div>
        {% if forloop.first or forloop.last %}
        <div class="image col-lg-5"><img src="{{ obj.thumbnail.url }}" alt="..."></div>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </section>
<!-- Divider Section-->
<section style="background: url(/static/a_images/3.JPG); background-size: cover; background-position: center bottom"
  class="divider">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h3>To me travelling was all about exploring and adventure, and exploring new places but at one point it was a
          part of me , and it always made a betterperson than I was before and it madea new person with a new thought
          with new vision.</h3>
      </div>
    </div>
  </div>
</section>
<!-- Latest Posts -->
<section class="latest-posts">
  <div class="container">
    <header>
      <h2>Latest from the blog</h2>
      <p class="text-big">Here some latest blog Added recently.</p>
    </header>
    <div class="row">
      {% for obj in latest %}
      <div class="post col-md-4">
        <div class="post-thumbnail"><a href="#"><img src="{{ obj.thumbnail.url }}" alt="..." class="img-fluid"></a>
        </div>
        <div class="post-details">
          <div class="post-meta d-flex justify-content-between">
            <div class="date">{{ obj.author.user.first_name }} {{ obj.author.user.last_name }}</div>
            <div class="date"><i class="icon-clock"></i>{{ obj.timestamp }}</div>
            <div class="category">
              {% for cat in obj.categories.all %}
              <a href="#">{{ cat }}</a>
              {% endfor %}
            </div>
          </div><a href="{{ obj.get_absolute_url }}">
            <h3 class="h4">{{ obj.title }}</h3>
          </a>
          <p class="text-muted">{{ obj.overview|linebreaks|truncatechars:200 }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- Newsletter Section-->
<section class="newsletter no-padding-top">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Subscribe to Newsletter</h2>
        <p class="text-big">Enter email and get notification when new blog post published. </p>
      </div>
      <div class="col-md-8">
        <div class="form-holder">
          <form action="{% url 'newsletter' %}" method="POST">
            {% csrf_token %}
                {{form}}
              <button type="submit" class="submit">Signup</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
      <div class="row">
        <main class="post blog-post col-lg-8"> 
          <div class="container">
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <form method="post">
                {% csrf_token %}
                <input class="btn btn-outline-danger" type="submit" value="Confirm">
              </form>
          </div>
        </main>
        {% include 'includes/sidebar.html' with most_recent=most_recent category_count=category_count %}
      </div>
    </div>
{% endblock content %}

templates/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-4 offset-4 mb-5 mt-5">
<h3>{{ title }} an article</h3>
{{ form.media }}
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-outline-secondary" type="submit">Submit</button>
</form>

</div>

{% endblock content %}

templates/search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
<br>
{% if queryset %}    
    <div class="card border-secondary col-md-6 mx-auto">
        <div class="card-header mx-auto">Results of your Search</div>
      {% for post in queryset %}
        <div  class="card-body text-secondary">
                    <ul id="results">
                        <li><a href="{{ post.get_absolute_url }}">{{ post.title}}</a></li>
                    </ul>
        </div>
        <hr class="sm">
     {% endfor %}
    </div>
{% else %}
<p style="text-align:center;"><img height="250" src="{% static 'img/wrongs.png' %}" alt="img"></p>
<h4 style="text-align:center;">Sorry, we couldn't find any matches.</h4>
<br>
{% endif %}
</div>
<br>
{% endblock %}